Intro
Pyrus-vagus/jet-start pull request #1
Opened 2021-08-13 15:33 UTC by Pyrus-vagus

1. Created a left menu and the main part to the right. Enabled switching between Contacts, Data and Settings subviews.

2. Contacts view contains a list of contacts and a form placed side by side. 

3. Data view contains a multiview with 2 tabs: Countries and Statuses. Enabled add/update/delete functionality.

3. Settings view contains a Segmented button for switching between languages. Currently locales are not applied.

2021-08-13 16:52 UTC, HelgaListopad requested changes

2021-08-13 16:52 UTC, HelgaListopad commented on sources/views/data/basicTable.js
> +    console.log(this._name);
логи оставлять не стоит

2021-08-13 16:52 UTC, HelgaListopad commented on sources/views/data/basicTable.js
> +          this.data.remove(id);
Как и добавление, удаление также должно происходить из коллекции

2021-08-13 16:52 UTC, HelgaListopad commented on sources/views/data/basicTable.js
> +    const tableData = this._componentData;
Здесь не сильно нужна эта переменная, так как ссылка на коллекцию у тебя уже есть, а onItemClick ты можешь сделать стрелочной.

2021-08-13 16:52 UTC, HelgaListopad commented on sources/views/data/basicTable.js
> +    console.log(this);
лог

2021-08-16 10:02 UTC, Pyrus-vagus commented on sources/views/data/basicTable.js
> +    console.log(this._name);
+

2021-08-16 10:03 UTC, Pyrus-vagus commented on sources/views/data/basicTable.js
> +          this.data.remove(id);
done

2021-08-16 10:03 UTC, Pyrus-vagus commented on sources/views/data/basicTable.js
> +    const tableData = this._componentData;
done

2021-08-16 10:03 UTC, Pyrus-vagus commented on sources/views/data/basicTable.js
> +    console.log(this);
done

2021-08-16 10:05 UTC, HelgaListopad approved these changes

2021-08-16 10:05 UTC, merged