Lesson 2
Pyrus-vagus/jet-start pull request #2
Opened 2021-08-17 12:46 UTC by Pyrus-vagus

1 . Singled out the form to a separate module. Connected list and form.
  + When the application is loaded, the first contact in the list is selected and the form is filled in with this contact’s data. 
  + Selected contact is reflected in the URL.

2. Added combo boxes to the form. Filled their options with countries and statuses data. 

3. Made it possible to add, remove and update contacts:  
 + add: via a button below the contacts list; 
 + delete: via an icon on each contact item;
 + update:via the related form (not binding).

4. Added localization via the already created button in Settings: EN and RU.

2021-08-17 16:47 UTC, HelgaListopad requested changes

2021-08-17 16:47 UTC, HelgaListopad commented on sources/views/contacts/form.js
> +    const id = this.getParam("id", true) || contacts.getFirstId();
Если id нет => не выбран контакт => форму лучше оставить пустой/очистить её на всякий случай

2021-08-17 16:47 UTC, HelgaListopad commented on sources/views/contacts/contacts.js
> +    contacts.waitData.then(() => {
Это лучше делать на ините.

Сейчас не работает эта часть
> When the application is loaded, the first contact in the list must be selected

Как и эта
> Ensure to reflect the selected contact in the URL. When users reload the page (F5), the previously shown contact should be selected.

2021-08-17 16:47 UTC, HelgaListopad commented on sources/views/contacts/contacts.js
> +      });
> Make sure that the newly added item is immediately set up for editing.

Необходимо сразу выбрать добавленную строку

2021-08-17 16:47 UTC, HelgaListopad commented on sources/views/contacts/contacts.js
> +          this.$$("list").select(item);
Что будет, если удалить последний существующий элемент?
Возможно, лучше не трогать существующий селект, если он не имеет отношение к удаляемому элементу.
А вот если удаляемая строка была выбрана, то очистить форму.

2021-08-17 16:47 UTC, HelgaListopad commented on sources/views/contacts/form.js
> +        newData.id ? contacts.updateItem(newData.id, newData) : "";
Смешивать выполнение какой-то логики и `: ""` не комильфо.
Проще написать if, чтобы не приходилось делать подобную заглушку

2021-08-18 09:49 UTC, Pyrus-vagus commented on sources/views/contacts/contacts.js
> +      });
+

2021-08-18 11:34 UTC, Pyrus-vagus commented on sources/views/contacts/form.js
> +    const id = this.getParam("id", true) || contacts.getFirstId();
done

2021-08-18 11:34 UTC, Pyrus-vagus commented on sources/views/contacts/contacts.js
> +    contacts.waitData.then(() => {
done

2021-08-18 11:34 UTC, Pyrus-vagus commented on sources/views/contacts/contacts.js
> +          this.$$("list").select(item);
done

2021-08-18 11:34 UTC, Pyrus-vagus commented on sources/views/contacts/form.js
> +        newData.id ? contacts.updateItem(newData.id, newData) : "";
done

2021-08-19 08:13 UTC, HelgaListopad commented on sources/views/contacts/contacts.js
> +      });
Переносить `attachEvent` в `waitData` нет смысла.
`add` вызывается только по клику, и здесь для операции + селекта того мы добавили локально промис не обязателен.

2021-08-19 08:13 UTC, HelgaListopad commented on sources/views/contacts/contacts.js
> +          this.$$("list").select(item);
Лучше тестировать такие вещи
Смотри, что будет сейчас, если селект на одной строке, а удалишь ты другую
![image](https://user-images.githubusercontent.com/7587383/130032791-e509149a-09d6-450f-b461-8b1146a84f98.png)

2021-08-19 08:16 UTC, HelgaListopad commented on sources/views/contacts/contacts.js
> +    contacts.waitData.then(() => {
Переносить `attachEvent` в `waitData` нет смысла.
`add` вызывается только по клику, и здесь для операции + селекта того мы добавили локально промис не обязателен.

2021-08-19 08:17 UTC, HelgaListopad commented on sources/views/contacts/contacts.js
> +      });
Переносить `attachEvent` в `waitData` нет смысла.
`add` вызывается только по клику, и здесь для операции + селекта того мы добавили локально промис не обязателен.

2021-08-19 09:01 UTC, Pyrus-vagus commented on sources/views/contacts/contacts.js
> +      });
done

2021-08-19 09:01 UTC, Pyrus-vagus commented on sources/views/contacts/contacts.js
> +          this.$$("list").select(item);
done

2021-08-19 09:27 UTC, HelgaListopad approved these changes

2021-08-19 09:27 UTC, merged