connect client to the server
Pyrus-vagus/jet-start pull request #3
Opened 2021-08-19 10:33 UTC by Pyrus-vagus

Connect frontend to backend

2021-08-19 21:41 UTC, HelgaListopad requested changes

2021-08-19 21:41 UTC, HelgaListopad commented on sources/views/contacts/contacts.js
> +          country ? country.Name : "ghost country"
Здесь всё верно, но помнишь, мы говорили, что когда данные в countries точно появятся, придётся вызвать перерисовку листа, чтобы их отобразить?
Следовательно, в ините не хватает countries.waitData => list.refresh()

2021-08-19 21:41 UTC, HelgaListopad commented on sources/views/contacts/form.js
>          this.webix.message("Information is updated!");
Сообщение теперь логично выводить в случае успешного апдейта: waitSave(() => updateItem).then(() => message)

2021-08-19 21:41 UTC, HelgaListopad commented on sources/views/contacts/contacts.js
> +          country ? country.Name : "ghost country"
Имитировать долгий ответ с сервера для теста можно так
https://snippet.webix.com/4px7e88c

2021-08-20 09:22 UTC, Pyrus-vagus commented on sources/views/contacts/form.js
>          this.webix.message("Information is updated!");
done

2021-08-20 09:22 UTC, Pyrus-vagus commented on sources/views/contacts/contacts.js
> +          country ? country.Name : "ghost country"
done

2021-08-20 09:57 UTC, HelgaListopad approved these changes

2021-08-20 09:57 UTC, merged